// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// Config is the golang structure for table sys_config.
type Config internal.Config

// Fill with you ideas below.
