// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// Department is the golang structure for table sys_department.
type Department internal.Department

// Fill with you ideas below.
