// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// Log is the golang structure for table sys_log.
type Log internal.Log

// Fill with you ideas below.
