// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// Menu is the golang structure for table sys_menu.
type Menu internal.Menu

// Fill with you ideas below.
