// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf/util/gconv"
	"gmanager/app/dao"
	"gmanager/app/model/internal"
)

// Role is the golang structure for table sys_role.
type Role internal.Role

// Fill with you ideas below.

func (role Role) PkVal() int {
	return gconv.Int(role.Id)
}

func (role Role) TableName() string {
	return dao.Role.Table
}

func (role Role) Columns() string {
	sqlColumns := "t.id,t.name,t.status,t.sort,t.remark,t.enable,t.update_time as updateTime,t.update_id as updateId,t.create_time as createTime,t.create_id as createId"
	return sqlColumns
}
