// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// RoleMenu is the golang structure for table sys_role_menu.
type RoleMenu internal.RoleMenu

// Fill with you ideas below.
