// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// Role is the golang structure for table sys_role.
type Role internal.Role

// Fill with you ideas below.
