// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf/util/gconv"
	"gmanager/app/dao"
	"gmanager/app/model/internal"
)

// User is the golang structure for table sys_user.
type User internal.User

// Fill with you ideas below.

func (user User) PkVal() int {
	return gconv.Int(user.Id)
}

func (user User) TableName() string {
	return dao.User.Table
}

func (user User) Columns() string {
	sqlColumns := "t.id,t.uuid,t.username,t.password,t.salt,t.real_name as realName,t.depart_id as departId,t.user_type as userType,t.status,t.thirdid,t.endtime,t.email,t.tel,t.address,t.title_url as titleUrl,t.remark,t.theme,t.back_site_id as backSiteId,t.create_site_id as createSiteId,t.project_id as projectId,t.project_name as projectName,t.enable,t.update_time as updateTime,t.update_id as updateId,t.create_time as createTime,t.create_id as createId"
	return sqlColumns
}
