// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gmanager/app/model/internal"
)

// UserRole is the golang structure for table sys_user_role.
type UserRole internal.UserRole

// Fill with you ideas below.
