// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gmanager/internal/admin/dao/internal"
)

// configDao is the data access object for the table sys_config.
// You can define custom methods on it to extend its functionality as needed.
type configDao struct {
	*internal.ConfigDao
}

var (
	// Config is a globally accessible object for table sys_config operations.
	Config = configDao{internal.NewConfigDao()}
)

// Add your custom methods and functionality below.
