// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gmanager/internal/admin/dao/internal"
)

// logDao is the data access object for the table sys_log.
// You can define custom methods on it to extend its functionality as needed.
type logDao struct {
	*internal.LogDao
}

var (
	// Log is a globally accessible object for table sys_log operations.
	Log = logDao{internal.NewLogDao()}
)

// Add your custom methods and functionality below.
