// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gmanager/internal/admin/dao/internal"
)

// userRoleDao is the data access object for the table sys_user_role.
// You can define custom methods on it to extend its functionality as needed.
type userRoleDao struct {
	*internal.UserRoleDao
}

var (
	// UserRole is a globally accessible object for table sys_user_role operations.
	UserRole = userRoleDao{internal.NewUserRoleDao()}
)

// Add your custom methods and functionality below.
