// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Menu is the golang structure for table sys_menu.
type Menu struct {
	Id         int    `orm:"id,primary"  json:"id"`         // 主键
	ParentId   int    `orm:"parent_id"   json:"parentId"`   // 父id
	Name       string `orm:"name"        json:"name"`       // 名称/11111
	Icon       string `orm:"icon"        json:"icon"`       // 菜单图标
	Urlkey     string `orm:"urlkey"      json:"urlkey"`     // 菜单key
	Url        string `orm:"url"         json:"url"`        // 链接地址
	Perms      string `orm:"perms"       json:"perms"`      // 授权(多个用逗号分隔，如：user:list,user:create)
	Status     int    `orm:"status"      json:"status"`     // 状态//radio/2,隐藏,1,显示
	Type       int    `orm:"type"        json:"type"`       // 类型//select/1,目录,2,菜单,3,按钮
	Sort       int    `orm:"sort"        json:"sort"`       // 排序
	Level      int    `orm:"level"       json:"level"`      // 级别
	Enable     int    `orm:"enable"      json:"enable"`     // 是否启用//radio/1,启用,2,禁用
	UpdateTime string `orm:"update_time" json:"updateTime"` // 更新时间
	UpdateId   int    `orm:"update_id"   json:"updateId"`   // 更新人
	CreateTime string `orm:"create_time" json:"createTime"` // 创建时间
	CreateId   int    `orm:"create_id"   json:"createId"`   // 创建者
}
