// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// RoleMenu is the golang structure for table sys_role_menu.
type RoleMenu struct {
	Id     int `orm:"id,primary" json:"id"`     // 主键
	RoleId int `orm:"role_id"    json:"roleId"` // 角色id
	MenuId int `orm:"menu_id"    json:"menuId"` // 菜单id
}
