// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// User is the golang structure for table sys_user.
type User struct {
	Id           int    `orm:"id,primary"      json:"id"`           // 主键
	Uuid         string `orm:"uuid"            json:"uuid"`         // UUID
	Username     string `orm:"username,unique" json:"username"`     // 登录名/11111
	Password     string `orm:"password"        json:"password"`     // 密码
	Salt         string `orm:"salt"            json:"salt"`         // 密码盐
	RealName     string `orm:"real_name"       json:"realName"`     // 真实姓名
	DepartId     int    `orm:"depart_id"       json:"departId"`     // 部门/11111/dict
	UserType     int    `orm:"user_type"       json:"userType"`     // 类型//select/1,管理员,2,普通用户,3,前台用户,4,第三方用户,5,API用户
	Status       int    `orm:"status"          json:"status"`       // 状态
	Thirdid      string `orm:"thirdid"         json:"thirdid"`      // 第三方ID
	Endtime      string `orm:"endtime"         json:"endtime"`      // 结束时间
	Email        string `orm:"email"           json:"email"`        // email
	Tel          string `orm:"tel"             json:"tel"`          // 手机号
	Address      string `orm:"address"         json:"address"`      // 地址
	TitleUrl     string `orm:"title_url"       json:"titleUrl"`     // 头像地址
	Remark       string `orm:"remark"          json:"remark"`       // 说明
	Theme        string `orm:"theme"           json:"theme"`        // 主题
	BackSiteId   int    `orm:"back_site_id"    json:"backSiteId"`   // 后台选择站点ID
	CreateSiteId int    `orm:"create_site_id"  json:"createSiteId"` // 创建站点ID
	ProjectId    int    `orm:"project_id"      json:"projectId"`    // 项目ID
	ProjectName  string `orm:"project_name"    json:"projectName"`  // 项目名称
	Enable       int    `orm:"enable"          json:"enable"`       // 是否启用//radio/1,启用,2,禁用
	UpdateTime   string `orm:"update_time"     json:"updateTime"`   // 更新时间
	UpdateId     int    `orm:"update_id"       json:"updateId"`     // 更新人
	CreateTime   string `orm:"create_time"     json:"createTime"`   // 创建时间
	CreateId     int    `orm:"create_id"       json:"createId"`     // 创建者

	DepartName string `json:"departName" gconv:"departName,omitempty"` // 项目名称
	UpdateName string `json:"updateName,omitempty" gconv:"updateName,omitempty"`
	CreateName string `json:"createName,omitempty" gconv:"createName,omitempty"`
}
