// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gmanager/app/dao/internal"
)

// configDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type configDao struct {
	*internal.ConfigDao
}

var (
	// Config is globally public accessible object for table sys_config operations.
	Config = configDao{
		internal.NewConfigDao(),
	}
)

// Fill with you ideas below.
