// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gmanager/internal/dao/internal"
)

// roleMenuDao is the data access object for the table sys_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type roleMenuDao struct {
	*internal.RoleMenuDao
}

var (
	// RoleMenu is a globally accessible object for table sys_role_menu operations.
	RoleMenu = roleMenuDao{internal.NewRoleMenuDao()}
)

// Add your custom methods and functionality below.
