// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gmanager/internal/dao/internal"
)

// userRoleCasbinDao is the data access object for the table sys_user_role_casbin.
// You can define custom methods on it to extend its functionality as needed.
type userRoleCasbinDao struct {
	*internal.UserRoleCasbinDao
}

var (
	// UserRoleCasbin is a globally accessible object for table sys_user_role_casbin operations.
	UserRoleCasbin = userRoleCasbinDao{internal.NewUserRoleCasbinDao()}
)

// Add your custom methods and functionality below.
