// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ConfigDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ConfigDao struct {
	gmvc.M                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB        // DB is the raw underlying database management object.
	Table   string        // Table is the table name of the DAO.
	Columns configColumns // Columns contains all the columns of Table that for convenient usage.
}

// ConfigColumns defines and stores column names for table sys_config.
type configColumns struct {
	Id           string // 主键
	Name         string // 名称
	Key          string // 键
	Value        string // 值
	Code         string // 编码
	DataType     string // 数据类型//radio/1,KV,2,字典,3,数组
	ParentId     string // 类型
	ParentKey    string //
	Sort         string // 排序号
	ProjectId    string // 项目ID
	CopyStatus   string // 拷贝状态 1 拷贝  2  不拷贝
	ChangeStatus string // 1 不可更改 2 可以更改
	Enable       string // 是否启用//radio/1,启用,2,禁用
	UpdateTime   string // 更新时间
	UpdateId     string // 更新人
	CreateTime   string // 创建时间
	CreateId     string // 创建者
}

func NewConfigDao() *ConfigDao {
	return &ConfigDao{
		M:     g.DB("default").Model("sys_config").Safe(),
		DB:    g.DB("default"),
		Table: "sys_config",
		Columns: configColumns{
			Id:           "id",
			Name:         "name",
			Key:          "key",
			Value:        "value",
			Code:         "code",
			DataType:     "data_type",
			ParentId:     "parent_id",
			ParentKey:    "parent_key",
			Sort:         "sort",
			ProjectId:    "project_id",
			CopyStatus:   "copy_status",
			ChangeStatus: "change_status",
			Enable:       "enable",
			UpdateTime:   "update_time",
			UpdateId:     "update_id",
			CreateTime:   "create_time",
			CreateId:     "create_id",
		},
	}
}
