// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// LogDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type LogDao struct {
	gmvc.M             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB     // DB is the raw underlying database management object.
	Table   string     // Table is the table name of the DAO.
	Columns logColumns // Columns contains all the columns of Table that for convenient usage.
}

// LogColumns defines and stores column names for table sys_log.
type logColumns struct {
	Id         string // 主键
	LogType    string // 类型
	OperObject string // 操作对象
	OperTable  string // 操作表
	OperId     string // 操作主键
	OperType   string // 操作类型
	OperRemark string // 操作备注
	Enable     string // 是否启用//radio/1,启用,2,禁用
	UpdateTime string // 更新时间
	UpdateId   string // 更新人
	CreateTime string // 创建时间
	CreateId   string // 创建者
}

func NewLogDao() *LogDao {
	return &LogDao{
		M:     g.DB("default").Model("sys_log").Safe(),
		DB:    g.DB("default"),
		Table: "sys_log",
		Columns: logColumns{
			Id:         "id",
			LogType:    "log_type",
			OperObject: "oper_object",
			OperTable:  "oper_table",
			OperId:     "oper_id",
			OperType:   "oper_type",
			OperRemark: "oper_remark",
			Enable:     "enable",
			UpdateTime: "update_time",
			UpdateId:   "update_id",
			CreateTime: "create_time",
			CreateId:   "create_id",
		},
	}
}
