// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RoleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RoleMenuDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns roleMenuColumns // Columns contains all the columns of Table that for convenient usage.
}

// RoleMenuColumns defines and stores column names for table sys_role_menu.
type roleMenuColumns struct {
	Id     string // 主键
	RoleId string // 角色id
	MenuId string // 菜单id
}

func NewRoleMenuDao() *RoleMenuDao {
	return &RoleMenuDao{
		M:     g.DB("default").Model("sys_role_menu").Safe(),
		DB:    g.DB("default"),
		Table: "sys_role_menu",
		Columns: roleMenuColumns{
			Id:     "id",
			RoleId: "role_id",
			MenuId: "menu_id",
		},
	}
}
