// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RoleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RoleDao struct {
	gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB      // DB is the raw underlying database management object.
	Table   string      // Table is the table name of the DAO.
	Columns roleColumns // Columns contains all the columns of Table that for convenient usage.
}

// RoleColumns defines and stores column names for table sys_role.
type roleColumns struct {
	Id         string // 主键
	Name       string // 名称/11111/
	Status     string // 状态//radio/2,隐藏,1,显示
	Sort       string // 排序
	Remark     string // 说明//textarea
	Enable     string // 是否启用//radio/1,启用,2,禁用
	UpdateTime string // 更新时间
	UpdateId   string // 更新人
	CreateTime string // 创建时间
	CreateId   string // 创建者
}

func NewRoleDao() *RoleDao {
	return &RoleDao{
		M:     g.DB("default").Model("sys_role").Safe(),
		DB:    g.DB("default"),
		Table: "sys_role",
		Columns: roleColumns{
			Id:         "id",
			Name:       "name",
			Status:     "status",
			Sort:       "sort",
			Remark:     "remark",
			Enable:     "enable",
			UpdateTime: "update_time",
			UpdateId:   "update_id",
			CreateTime: "create_time",
			CreateId:   "create_id",
		},
	}
}
