// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// RoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type RoleDao struct {
	Table   string      // Table is the underlying table name of the DAO.
	Group   string      // Group is the database configuration group name of current DAO.
	Columns RoleColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// RoleColumns defines and stores column names for table sys_role.
type RoleColumns struct {
	Id         string // 主键
	Name       string // 名称/11111/
	Status     string // 状态//radio/2,隐藏,1,显示
	Sort       string // 排序
	Remark     string // 说明//textarea
	Enable     string // 是否启用//radio/1,启用,2,禁用
	UpdateTime string // 更新时间
	UpdateId   string // 更新人
	CreateTime string // 创建时间
	CreateId   string // 创建者
}

//  roleColumns holds the columns for table sys_role.
var roleColumns = RoleColumns{
	Id:         "id",
	Name:       "name",
	Status:     "status",
	Sort:       "sort",
	Remark:     "remark",
	Enable:     "enable",
	UpdateTime: "update_time",
	UpdateId:   "update_id",
	CreateTime: "create_time",
	CreateId:   "create_id",
}

// NewRoleDao creates and returns a new DAO object for table data access.
func NewRoleDao() *RoleDao {
	return &RoleDao{
		Group:   "default",
		Table:   "sys_role",
		Columns: roleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RoleDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
