// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserRoleDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns userRoleColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserRoleColumns defines and stores column names for table sys_user_role.
type userRoleColumns struct {
	Id     string // 主键
	UserId string // 用户id
	RoleId string // 角色id
}

func NewUserRoleDao() *UserRoleDao {
	return &UserRoleDao{
		M:     g.DB("default").Model("sys_user_role").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user_role",
		Columns: userRoleColumns{
			Id:     "id",
			UserId: "user_id",
			RoleId: "role_id",
		},
	}
}
