// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserDao struct {
	gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB      // DB is the raw underlying database management object.
	Table   string      // Table is the table name of the DAO.
	Columns userColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserColumns defines and stores column names for table sys_user.
type userColumns struct {
	Id           string // 主键
	Uuid         string // UUID
	Username     string // 登录名/11111
	Password     string // 密码
	Salt         string // 密码盐
	RealName     string // 真实姓名
	DepartId     string // 部门/11111/dict
	UserType     string // 类型//select/1,管理员,2,普通用户,3,前台用户,4,第三方用户,5,API用户
	Status       string // 状态
	Thirdid      string // 第三方ID
	Endtime      string // 结束时间
	Email        string // email
	Tel          string // 手机号
	Address      string // 地址
	TitleUrl     string // 头像地址
	Remark       string // 说明
	Theme        string // 主题
	BackSiteId   string // 后台选择站点ID
	CreateSiteId string // 创建站点ID
	ProjectId    string // 项目ID
	ProjectName  string // 项目名称
	Enable       string // 是否启用//radio/1,启用,2,禁用
	UpdateTime   string // 更新时间
	UpdateId     string // 更新人
	CreateTime   string // 创建时间
	CreateId     string // 创建者
}

func NewUserDao() *UserDao {
	return &UserDao{
		M:     g.DB("default").Model("sys_user").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user",
		Columns: userColumns{
			Id:           "id",
			Uuid:         "uuid",
			Username:     "username",
			Password:     "password",
			Salt:         "salt",
			RealName:     "real_name",
			DepartId:     "depart_id",
			UserType:     "user_type",
			Status:       "status",
			Thirdid:      "thirdid",
			Endtime:      "endtime",
			Email:        "email",
			Tel:          "tel",
			Address:      "address",
			TitleUrl:     "title_url",
			Remark:       "remark",
			Theme:        "theme",
			BackSiteId:   "back_site_id",
			CreateSiteId: "create_site_id",
			ProjectId:    "project_id",
			ProjectName:  "project_name",
			Enable:       "enable",
			UpdateTime:   "update_time",
			UpdateId:     "update_id",
			CreateTime:   "create_time",
			CreateId:     "create_id",
		},
	}
}
