// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// UserRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type UserRoleDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns UserRoleColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// UserRoleColumns defines and stores column names for table sys_user_role.
type UserRoleColumns struct {
	Id     string // 主键
	UserId string // 用户id
	RoleId string // 角色id
}

//  userRoleColumns holds the columns for table sys_user_role.
var userRoleColumns = UserRoleColumns{
	Id:     "id",
	UserId: "user_id",
	RoleId: "role_id",
}

// NewUserRoleDao creates and returns a new DAO object for table data access.
func NewUserRoleDao() *UserRoleDao {
	return &UserRoleDao{
		Group:   "default",
		Table:   "sys_user_role",
		Columns: userRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserRoleDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
